spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://43.138.103.83:3306/xdu_hospital?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: Xdu000000
  redis:
    host: 43.138.103.83
    port: 6379
    password: Xdu000000

mybatis-plus:
  configuration:
    #配置驼峰命名
    map-underscore-to-camel-case: true
    #plus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

weixin:
  appid: wx535c17fd80210503
  secret:


#aliyun OSS存储配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tC2jMwic1TTHWun2Aqe
      keysecret: sRzv3VQxH5Vyxl9AUcidkoxj76nbUE
      bucketname: bucket-20020501
