spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.108.112.99:3306/xdu_hospital?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: Xdu000000
  redis:
    host: 47.108.112.99
    port: 6379
    password: kkkkkk

mybatis-plus:
  configuration:
    #配置驼峰命名
    map-underscore-to-camel-case: true
    #plus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

weixin:
  appid: wx544318af0bac3c1b
  secret: d83791872c433113abddda069aaed818


#aliyun OSS存储配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: 
      keysecret: 
      bucketname: bucket-20020501
