spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xdu_hospital?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: Ksy521...
  redis:
    host: 47.108.112.99
    port: 6379
    password: kkkkkk

mybatis-plus:
  configuration:
    #配置驼峰命名
    map-underscore-to-camel-case: true
    #plus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

weixin:
  appid: wx544318af0bac3c1b
  secret: d83791872c433113abddda069aaed818